[package]
name = "pir-player"
version = "0.1.0"
authors = ["Alexander Hildebrandt <alex@hilde.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio = "0.4.1"
rand = "0.8.4"